language: php

# list any PHP version you want to test against
php:
  - 7.0
  - 7.1
  - 7.2
  - hhvm
  - nightly

install:
   - composer install

script: vendor/bin/phpunit --verbose --coverage-clover=coverage.clover